### ISSUE TITLE
Subdomain enum Error

### ISSUE THREAD

**Issue by d4op** [klezVirus/vortex#4]
python3.9 vortex.py -w m subdomain -c enum -D google.com

   ,d#####F^      ,yy############yy       ^9#######,
  ,######"      y###################by      ^9######,
  ######^     y#####F""       ^"9######y      "######]
 d#####^    ,#####" by klezVirus ^9#####,     ^######,
,#####]    ,####F    yy#######y,    ^9####b     ^######
[#####     ####F   ,###F""'"9####,    9####]     9#####
#####F    [####   ,##F^  yy   "###b    9####,    ^#####]
#####]    [###]   ###  dF""#b  ^###]   ^####]     #####]
9####b    [####   9##, 9bd [#]  [##b    #####     [#####
[#####     ####,   9##y, ,y##^  d##F    #####     [####]
 #####b    ^####y   ^"#####"   d###^   ,####]     d#####
 [#####,    ^####by          ,d###^    d####^     #####F
  9#####y     "#####byyyyyyd####F^    d####F     [#####9
   9#####b,     ""############"^    ,d####F     ,######
    ^######b,       ""'""'"^      ,d#####F      d#####F

[*] Starting subdomain passive enumeration
[*] Starting subdomain enumeration with `Amass`
"/root/go/bin/amass" enum  -rf "/root/vortex/lib/Sublist3r/subbrute/resolvers.txt" -nf "/root/vortex/lib/Sublist3r/subbrute/names.txt" -d google.com -passive
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/vortex/vortex.py", line 75, in run
    action_instance.safe_execute(**self.action_vargs)
  File "/root/vortex/actions/action.py", line 161, in safe_execute
    self.execute(**kwargs)
  File "/root/vortex/actions/subdomain.py", line 151, in execute
    amass.enumerate()
  File "/root/vortex/lib/Amass.py", line 106, in enumerate
    self.__execute()
  File "/root/vortex/lib/Amass.py", line 124, in __execute
    process = subprocess.Popen(cmd, stdout=writer, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '"/root/go/bin/amass" enum  -rf "/root/vortex/lib/Sublist3r/subbrute/resolvers.txt" -nf "/root/vortex/lib/Sublist3r/subbrute/names.txt" -d google.com -passive'

the file /root/go/bin/amass exists and is executable
no idea why this pops up.

**Comment by d4op** [comment]
manually 
"/root/go/bin/amass" enum -rf "/root/vortex/lib/Sublist3r/subbrute/resolvers.txt" -nf "/root/vortex/lib/Sublist3r/subbrute/names.txt" -d google.com -passive

works in terminal.
permissions and path are correct, still wondering why i get this error above.

**Comment by d4op** [comment]
vortex-master works good with with domain -c enum no error but dev branche gave me this errors above.
